const Types= {
    CHANGE_EMAIL : 'CHANGE_EMAIL',
    CHANGE_PASSWORD : 'CHANGE_PASSWORD',
    LOADING : 'LOADING',
    AUTH_SUCSESS : 'AUTH_SUCCESS',
    ERROR_LOGIN :'ERROR_LOGIN',
    LOAD_PRODUCT_DETAIL : 'LOAD_PRODUCT_DETAIL',
    LOADING_PRODUCT_DETAIL : 'LOADING_PRODUCT_DETAIL',
    FINISH_LOADING_DETAIL : 'FINISH_LOADING_DETAIL'
}

export default Types